version: "3.7"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=david
      - MONGO_PASSWORD=password
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.angular
    depends_on:
      - backend
      - nginx

  cypress:
    image: "cypress/included:10.0.2"
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:4200
    working_dir: /cypress
    volumes:
      - ./frontend/cypress:/cypress

  mongo:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=david
      - MONGO_INITDB_ROOT_PASSWORD=password
    # volumes:
    # - mongo-db:/data/db
# volumes:
#   mongo-db:
